version: "2"
services:
  backend:
    image: "__REGISTRY_NAME__/nginx-backend:__VERSION_NGINX_BACKEND__"
    environment:
      - constraint:pool_id==default
      - "occs:description=The nginx backends will be load balanced dynamically using service discovery."
    ports:
      - 80/tcp
  loadbalancer:
    image: "__REGISTRY_NAME__/nginx-lb:__VERSION_NGINX_LB__"
    environment:
      - "OCCS_API_TOKEN={{api_token}}"
      - "KV_IP=172.17.0.1"
      - "KV_PORT=9109"
      - "OCCS_BACKEND_KEY={{sd_deployment_containers_path \"backend\" 80}}"
      - "OCCS_HEALTHCHECK_HTTP=http://:8885/?timeout=10s&interval=30s"
      - "occs:description=This is a nginx loadbalancer with nginx backends. Visit port 8885 on the host running the loadbalancer to view the running example. Because this service has a static host-bound port, only one deployment can be done per host without getting port conflicts."
    ports:
      - "8885:80/tcp"
