version: "2"
services:
  backend:
    image: "__REGISTRY_NAME__/apache-backend:__VERSION_APACHE_BACKEND__"
    environment:
      - constraint:pool_id==default
      - "occs:description=The Apache backends will be load balanced dynamically using service discovery."
    ports:
      - 80/tcp
  loadbalancer:
    image: "__REGISTRY_NAME__/haproxy:__VERSION_HAPROXY__"
    environment:
      - "OCCS_API_TOKEN={{api_token}}"
      - "KV_IP=172.17.0.1"
      - "KV_PORT=9109"
      - "OCCS_BACKEND_KEY={{sd_deployment_containers_path \"backend\" 80}}"
      - "OCCS_HEALTHCHECK_HTTP=http://:8886/?timeout=10s&interval=30s"
      - "occs:description=This is a HA Proxy loadbalancer with Apache backends. Visit port 8886 on the host running the loadbalancer to view the running example. Because this service has a static host-bound port, only one deployment can be done per host without getting port conflicts."
    ports:
      - "8886:5000/tcp"
      - "1936:1936/tcp"
