apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wlserver-pvc-1
  labels:
    app: wls-server 
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wlserver-pvc-2
  labels:
    app: wls-server 
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
