apiVersion: apps/v1beta1 # for versions before 1.6.0 use extensions/v1beta1
kind: StatefulSet
metadata:
  name: managed-server
spec:
  serviceName: wls-subdomain
  replicas: 2
  template:
    metadata:
      name: ms
      labels:
        app: managed-server 
    spec:
      subdomain: wls-subdomain
      containers:
      - name: managed-server
        image: wls-k8s-domain 
        imagePullPolicy: Never
        command: ["sh"]
        args: ["/u01/oracle/startms.sh"]
        readinessProbe:
            httpGet:
              path: /weblogic/ready
              port: 8011
            initialDelaySeconds: 15
            timeoutSeconds: 5
        ports:
        - containerPort: 8011
        env:
        - name: JAVA_OPTIONS
          value: "-Dweblogic.StdoutDebugEnabled=true"
        - name: USER_MEM_ARGS
          value: "-Xms64m -Xmx256m "
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: DNS_DOMAIN_NAME
          value: "wls-subdomain"
        - name: WLUSER
          valueFrom:
            secretKeyRef:
              name: wlsecret
              key: username
        - name: WLPASSWORD
          valueFrom:
            secretKeyRef:
              name: wlsecret
              key: password

        volumeMounts:
        - mountPath: /u01/wlsdomain
          name: domain-home
        - mountPath: /u01/filestores
          name: filestore-data 
 
      volumes:
      - name: domain-home
        persistentVolumeClaim:
          claimName: wlserver-pvc-1
      - name: filestore-data
        persistentVolumeClaim:
          claimName: wlserver-pvc-2
---

apiVersion: v1 # headless service required for statefulSet
kind: Service
metadata:
  name: wls-subdomain
  labels:
    app: managed-server 
spec:
  ports:
  - name: client
    port: 8011
    protocol: TCP
    targetPort: 8011
  clusterIP: None
  selector:
    app: managed-server

---

apiVersion: v1
kind: Service
metadata:
  name: wls-service
  labels:
    app: managed-server 
spec:
  type: NodePort
  ports:
  - name: client
    port: 8011
    protocol: TCP
    targetPort: 8011
    nodePort: 30009
  selector:
    app: managed-server 


